/** Map Czech cities to their region (kraj). */
const CITY_REGIONS: Record<string, string> = {
  'praha': 'Praha',
  'brno': 'Jihomoravský',
  'ostrava': 'Moravskoslezský',
  'plzeň': 'Plzeňský',
  'liberec': 'Liberecký',
  'olomouc': 'Olomoucký',
  'české budějovice': 'Jihočeský',
  'hradec králové': 'Královéhradecký',
  'ústí nad labem': 'Ústecký',
  'pardubice': 'Pardubický',
  'zlín': 'Zlínský',
  'jihlava': 'Vysočina',
  'karlovy vary': 'Karlovarský',
  'kladno': 'Středočeský',
  'most': 'Ústecký',
  'opava': 'Moravskoslezský',
  'frýdek-místek': 'Moravskoslezský',
  'karviná': 'Moravskoslezský',
  'teplice': 'Ústecký',
  'děčín': 'Ústecký',
  'chomutov': 'Ústecký',
  'jablonec nad nisou': 'Liberecký',
  'mladá boleslav': 'Středočeský',
  'prostějov': 'Olomoucký',
  'přerov': 'Olomoucký',
  'česká lípa': 'Liberecký',
  'třebíč': 'Vysočina',
  'třinec': 'Moravskoslezský',
  'tábor': 'Jihočeský',
  'znojmo': 'Jihomoravský',
  'příbram': 'Středočeský',
  'cheb': 'Karlovarský',
  'kolín': 'Středočeský',
  'trutnov': 'Královéhradecký',
  'písek': 'Jihočeský',
  'kroměříž': 'Zlínský',
  'vsetín': 'Zlínský',
  'šumperk': 'Olomoucký',
  'uherské hradiště': 'Zlínský',
  'břeclav': 'Jihomoravský',
  'havířov': 'Moravskoslezský',
  'český krumlov': 'Jihočeský',
  'benešov': 'Středočeský',
  'beroun': 'Středočeský',
  'kutná hora': 'Středočeský',
  'nymburk': 'Středočeský',
  'rakovník': 'Středočeský',
  'mělník': 'Středočeský',
  'sokolov': 'Karlovarský',
  'jičín': 'Královéhradecký',
  'náchod': 'Královéhradecký',
  'rychnov nad kněžnou': 'Královéhradecký',
  'svitavy': 'Pardubický',
  'ústí nad orlicí': 'Pardubický',
  'chrudim': 'Pardubický',
  'havlíčkův brod': 'Vysočina',
  'pelhřimov': 'Vysočina',
  'žďár nad sázavou': 'Vysočina',
  'blansko': 'Jihomoravský',
  'hodonín': 'Jihomoravský',
  'vyškov': 'Jihomoravský',
  'nový jičín': 'Moravskoslezský',
  'bruntál': 'Moravskoslezský',
  'jeseník': 'Olomoucký',
  'strakonice': 'Jihočeský',
  'prachatice': 'Jihočeský',
  'jindřichův hradec': 'Jihočeský',
  'domažlice': 'Plzeňský',
  'klatovy': 'Plzeňský',
  'rokycany': 'Plzeňský',
  'tachov': 'Plzeňský',
  'louny': 'Ústecký',
  'litoměřice': 'Ústecký',
  'semily': 'Liberecký',
  'frenštát pod radhoštěm': 'Moravskoslezský',
  'bedřichov': 'Liberecký',
};

/** Look up the region (kraj) for a Czech city. Case-insensitive. */
export function getRegion(city: string): string | null {
  return CITY_REGIONS[city.toLowerCase().trim()] ?? null;
}
