import { createClient } from '@supabase/supabase-js';
import 'dotenv/config';

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const COUNTRY = 'CZ';

const races = [
  {
    slug: 'maraton-praha-2026',
    country: COUNTRY,
    name: 'Volkswagen Maraton Praha 2026',
    description:
      'Nejstarší a nejprestižnější maraton v České republice. Trasa vede historickým centrem Prahy podél Vltavy. Závod je součástí série Abbott World Marathon Majors candidates a přiláká tisíce běžců z celého světa.',
    date_start: '2026-05-10',
    time_start: '09:00',
    city: 'Praha',
    region: 'Praha',
    lat: 50.0755,
    lng: 14.4378,
    venue: 'Staroměstské náměstí',
    distances: [
      { label: 'Maraton', km: 42.195 },
      { label: 'Štafeta', km: 42.195 },
    ],
    terrain: 'road' as const,
    elevation_gain: 120,
    price_from: 1200,
    price_to: 2500,
    website: 'https://www.runczech.com/cs/udalosti/volkswagen-maraton-praha/',
    registration_url: 'https://www.runczech.com/cs/udalosti/volkswagen-maraton-praha/registrace/',
    organizer: 'RunCzech',
    organizer_url: 'https://www.runczech.com',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 10000,
    tags: ['maraton', 'iaaf', 'worldathletics'],
  },
  {
    slug: 'jarni-beh-smetanovy-sady-2026',
    country: COUNTRY,
    name: 'Jarní běh Smetanovy sady 2026',
    description:
      'Jarní závod v parku Smetanovy sady v centru Ústí nad Labem. Přátelská atmosféra, vhodné pro začátečníky.',
    date_start: '2026-04-18',
    time_start: '10:00',
    city: 'Ústí nad Labem',
    region: 'Ústecký',
    lat: 50.6607,
    lng: 14.0323,
    venue: 'Smetanovy sady',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
      { label: '2 km', km: 2 },
    ],
    terrain: 'road' as const,
    elevation_gain: 25,
    price_from: 200,
    price_to: 350,
    organizer: 'TJ Ústí',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 800,
    tags: ['10k', '5k', 'zacatecnici'],
  },
  {
    slug: 'karlovy-vary-pulmaraton-2026',
    country: COUNTRY,
    name: 'Mattoni Půlmaraton Karlovy Vary 2026',
    description:
      'Půlmaraton lázeňským městem. Součást série Mattoni. Trasa vede přes kolonády, podél Teplé a nabízí unikátní atmosféru lázeňského města.',
    date_start: '2026-05-23',
    time_start: '10:00',
    city: 'Karlovy Vary',
    region: 'Karlovarský',
    lat: 50.2325,
    lng: 12.8714,
    distances: [{ label: 'Půlmaraton', km: 21.1 }],
    terrain: 'road' as const,
    elevation_gain: 180,
    price_from: 650,
    price_to: 1100,
    website: 'https://www.runczech.com/cs/udalosti/mattoni-pulmaraton-karlovy-vary/',
    organizer: 'RunCzech',
    organizer_url: 'https://www.runczech.com',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 4000,
    tags: ['pulmaraton', 'runczech'],
  },
  {
    slug: 'liberecky-mestsky-beh-2026',
    country: COUNTRY,
    name: 'Liberecký městský běh 2026',
    description:
      'Městský závod v Liberci s trasou kolem přehrady a pod Ještědem. Krásné výhledy na Jizerské hory.',
    date_start: '2026-05-30',
    time_start: '10:00',
    city: 'Liberec',
    region: 'Liberecký',
    lat: 50.7663,
    lng: 15.0543,
    venue: 'Náměstí Dr. E. Beneše',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
    ],
    terrain: 'road' as const,
    elevation_gain: 100,
    price_from: 300,
    price_to: 450,
    organizer: 'TJ Liberec',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 1200,
    tags: ['10k', '5k'],
  },
  {
    slug: 'pulmaraton-ceske-budejovice-2026',
    country: COUNTRY,
    name: 'Půlmaraton České Budějovice 2026',
    description:
      'Rovný a rychlý půlmaraton v jihočeské metropoli. Ideální na osobní rekord. Trasa vede centrem města kolem řeky Malše a Vltavy.',
    date_start: '2026-06-06',
    time_start: '10:00',
    city: 'České Budějovice',
    region: 'Jihočeský',
    lat: 48.9745,
    lng: 14.4746,
    venue: 'Náměstí Přemysla Otakara II.',
    distances: [{ label: 'Půlmaraton', km: 21.1 }],
    terrain: 'road' as const,
    elevation_gain: 50,
    price_from: 600,
    price_to: 900,
    website: 'https://www.pulmaratonbudejovice.cz',
    organizer: 'Běžecký klub ČB',
    status: 'confirmed' as const,
    source: 'seed',
    tags: ['pulmaraton'],
  },
  {
    slug: 'obstacle-race-brno-2026',
    country: COUNTRY,
    name: 'Gladiator Race Brno 2026',
    description:
      'Největší překážkový závod na Moravě. Trasa areálem brněnského výstaviště s více než 30 překážkami. Kategorie pro začátečníky i pokročilé.',
    date_start: '2026-06-14',
    time_start: '09:00',
    city: 'Brno',
    region: 'Jihomoravský',
    lat: 49.1875,
    lng: 16.583,
    venue: 'Výstaviště Brno',
    distances: [
      { label: 'Elite 12 km', km: 12 },
      { label: 'Open 6 km', km: 6 },
      { label: 'Fun 3 km', km: 3 },
    ],
    terrain: 'obstacle' as const,
    price_from: 800,
    price_to: 1500,
    organizer: 'Gladiator Race s.r.o.',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 3000,
    tags: ['prekazky', 'ocr'],
  },
  {
    slug: 'runczech-pulmaraton-olomouc-2026',
    country: COUNTRY,
    name: 'RunCzech Půlmaraton Olomouc 2026',
    description:
      'Půlmaraton v historickém centru Olomouce. Součást série RunCzech. Trasa vede kolem barokních kašen a sloupů UNESCO.',
    date_start: '2026-06-20',
    time_start: '10:00',
    city: 'Olomouc',
    region: 'Olomoucký',
    lat: 49.5938,
    lng: 17.2509,
    venue: 'Horní náměstí',
    distances: [{ label: 'Půlmaraton', km: 21.1 }],
    terrain: 'road' as const,
    elevation_gain: 90,
    price_from: 700,
    price_to: 1200,
    website: 'https://www.runczech.com/cs/udalosti/pulmaraton-olomouc/',
    organizer: 'RunCzech',
    organizer_url: 'https://www.runczech.com',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 6000,
    tags: ['pulmaraton', 'runczech'],
  },
  {
    slug: 'zlinske-asfaltky-2026',
    country: COUNTRY,
    name: 'Zlínské Asfaltky 2026',
    description:
      'Tradiční letní závod na 10 km a 5 km v Baťově městě. Rychlá a rovná trasa centrem Zlína. Skvělá atmosféra a organizace.',
    date_start: '2026-06-28',
    time_start: '17:00',
    city: 'Zlín',
    region: 'Zlínský',
    lat: 49.2265,
    lng: 17.6669,
    venue: 'Náměstí Míru',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
    ],
    terrain: 'road' as const,
    elevation_gain: 40,
    price_from: 300,
    price_to: 450,
    organizer: 'AK Zlín',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 1500,
    tags: ['10k', '5k'],
  },
  {
    slug: 'cross-lipno-2026',
    country: COUNTRY,
    name: 'Cross kolem Lipna 2026',
    description:
      'Crossový závod kolem Lipenské přehrady. Kombinace lesních cest, luk a pláží. Ideální pro rodiny i závodníky.',
    date_start: '2026-07-04',
    time_start: '10:00',
    city: 'Lipno nad Vltavou',
    region: 'Jihočeský',
    lat: 48.6312,
    lng: 14.2222,
    venue: 'Marina Lipno',
    distances: [
      { label: '15 km', km: 15 },
      { label: '7 km', km: 7 },
    ],
    terrain: 'cross' as const,
    elevation_gain: 320,
    price_from: 400,
    price_to: 600,
    organizer: 'Lipno Sport',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 600,
    tags: ['cross', 'priroda'],
  },
  {
    slug: 'nocni-beh-ostravou-2026',
    country: COUNTRY,
    name: 'Noční běh Ostravou 2026',
    description:
      'Večerní závod osvětlenými ulicemi Ostravy. Unikátní atmosféra s průběhem přes industriální památky Dolní oblasti Vítkovice.',
    date_start: '2026-07-11',
    time_start: '21:00',
    city: 'Ostrava',
    region: 'Moravskoslezský',
    lat: 49.8209,
    lng: 18.2625,
    venue: 'Dolní oblast Vítkovice',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
    ],
    terrain: 'road' as const,
    elevation_gain: 60,
    price_from: 400,
    price_to: 550,
    organizer: 'Running Ostrava',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 2000,
    tags: ['10k', '5k', 'nocni'],
  },
  {
    slug: 'beskydy-trail-2026',
    country: COUNTRY,
    name: 'Beskydský Ultra Trail 2026',
    description:
      'Náročný ultra trailový závod přes hlavní hřeben Beskyd. Překonáte Lysou horu, Smrk i Radhošť. Jeden z nejtěžších trailů na Moravě.',
    date_start: '2026-07-25',
    time_start: '05:00',
    city: 'Frenštát pod Radhoštěm',
    region: 'Moravskoslezský',
    lat: 49.5481,
    lng: 18.2108,
    distances: [
      { label: 'Ultra 70 km', km: 70 },
      { label: 'Trail 35 km', km: 35 },
    ],
    terrain: 'trail' as const,
    elevation_gain: 3200,
    price_from: 900,
    price_to: 1800,
    website: 'https://www.beskydytrail.cz',
    organizer: 'Beskydský spolek',
    status: 'confirmed' as const,
    source: 'seed',
    tags: ['ultra', 'trail', 'hory'],
  },
  {
    slug: 'sumava-ultra-trail-2026',
    country: COUNTRY,
    name: 'Šumava Ultra Trail 2026',
    description:
      'Náročný ultratrail srdcem Šumavy. Trasa vede přes Boubín, Zhůří a kolem Čertova jezera. Divoká příroda národního parku.',
    date_start: '2026-08-01',
    time_start: '04:00',
    city: 'Vimperk',
    region: 'Jihočeský',
    lat: 49.0586,
    lng: 13.7848,
    distances: [
      { label: 'Ultra 80 km', km: 80 },
      { label: 'Trail 40 km', km: 40 },
      { label: 'Mini 20 km', km: 20 },
    ],
    terrain: 'trail' as const,
    elevation_gain: 2800,
    price_from: 1000,
    price_to: 2200,
    organizer: 'Šumava Runners',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 400,
    tags: ['ultra', 'trail', 'hory', 'narodni-park'],
  },
  {
    slug: 'krusnohorsky-maraton-2026',
    country: COUNTRY,
    name: 'Krušnohorský maraton 2026',
    description:
      'Horský maraton přes hřebeny Krušných hor. Trasa z Jáchymova do Karlových Varů s převýšením přes 1 500 metrů. Nádherné výhledy na obě strany hranice.',
    date_start: '2026-08-08',
    time_start: '07:00',
    city: 'Jáchymov',
    region: 'Karlovarský',
    lat: 50.3583,
    lng: 12.9083,
    distances: [
      { label: 'Maraton', km: 42.195 },
      { label: 'Půlmaraton', km: 21.1 },
    ],
    terrain: 'trail' as const,
    elevation_gain: 1500,
    price_from: 800,
    price_to: 1500,
    organizer: 'KH Sport',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 800,
    tags: ['maraton', 'trail', 'hory'],
  },
  {
    slug: 'vltava-run-2026',
    country: COUNTRY,
    name: 'Vltava Run 2026',
    description:
      'Legendární ultramaratonský závod podél Vltavy z Českého Krumlova do Prahy. 350 km přes 4 dny. Jeden z nejdelších etapových závodů v Evropě.',
    date_start: '2026-08-18',
    date_end: '2026-08-21',
    time_start: '06:00',
    city: 'Český Krumlov',
    region: 'Jihočeský',
    lat: 48.8127,
    lng: 14.3175,
    distances: [
      { label: '350 km', km: 350 },
      { label: '200 km', km: 200 },
      { label: '100 km', km: 100 },
    ],
    terrain: 'ultra' as const,
    elevation_gain: 4500,
    price_from: 3500,
    price_to: 8000,
    website: 'https://www.vltavarun.cz',
    registration_url: 'https://www.vltavarun.cz/registrace',
    organizer: 'Vltava Run s.r.o.',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 500,
    tags: ['ultra', 'vicedenni'],
  },
  {
    slug: 'plzensky-pulmaraton-2026',
    country: COUNTRY,
    name: 'Plzeňský půlmaraton 2026',
    description:
      'Půlmaraton městem piva. Trasa vede kolem Plzeňského Prazdroje, přes historické centrum a podél řeky Radbuzy. Pivní občerstvení v cíli.',
    date_start: '2026-09-05',
    time_start: '09:00',
    city: 'Plzeň',
    region: 'Plzeňský',
    lat: 49.7384,
    lng: 13.3736,
    venue: 'Náměstí Republiky',
    distances: [
      { label: 'Půlmaraton', km: 21.1 },
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
    ],
    terrain: 'road' as const,
    elevation_gain: 80,
    price_from: 500,
    price_to: 900,
    organizer: 'Run Plzeň',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 4000,
    tags: ['pulmaraton', '10k', '5k'],
  },
  {
    slug: 'jizerska-50-2026',
    country: COUNTRY,
    name: 'Jizerská 50 Trail 2026',
    description:
      'Tradiční trail závod v Jizerských horách. Krásná příroda a náročný terén. Závod prověří vaši kondici i orientaci v lese.',
    date_start: '2026-09-12',
    time_start: '08:00',
    city: 'Bedřichov',
    region: 'Liberecký',
    lat: 50.7847,
    lng: 15.1506,
    distances: [
      { label: '50 km', km: 50 },
      { label: '25 km', km: 25 },
    ],
    terrain: 'trail' as const,
    elevation_gain: 1800,
    price_from: 800,
    price_to: 1400,
    website: 'https://www.jizerska50.cz',
    organizer: 'SKI Klub Jizerská 50',
    status: 'confirmed' as const,
    source: 'seed',
    tags: ['trail', 'hory'],
  },
  {
    slug: 'pardubicky-vinobrani-10k-2026',
    country: COUNTRY,
    name: 'Pardubický vinařský 10K 2026',
    description:
      'Populární městská desítka v Pardubicích s občerstvením na trati. Skvělá atmosféra díky vinařskému festivalu v okolí.',
    date_start: '2026-09-26',
    time_start: '10:00',
    city: 'Pardubice',
    region: 'Pardubický',
    lat: 50.0343,
    lng: 15.7812,
    venue: 'Třída Míru',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
    ],
    terrain: 'road' as const,
    elevation_gain: 30,
    price_from: 350,
    price_to: 500,
    organizer: 'AK Pardubice',
    status: 'confirmed' as const,
    source: 'seed',
    tags: ['10k', '5k'],
  },
  {
    slug: 'brno-city-run-2026',
    country: COUNTRY,
    name: 'Brno City Run 2026',
    description:
      'Městský závod centrem Brna. Trasa vede přes Špilberk, kolem katedrály a Zelného trhu. Půlmaraton a kratší vzdálenosti.',
    date_start: '2026-10-03',
    time_start: '09:00',
    city: 'Brno',
    region: 'Jihomoravský',
    lat: 49.1951,
    lng: 16.6068,
    venue: 'Náměstí Svobody',
    distances: [
      { label: 'Půlmaraton', km: 21.1 },
      { label: '10 km', km: 10 },
    ],
    terrain: 'road' as const,
    elevation_gain: 150,
    price_from: 600,
    price_to: 1100,
    organizer: 'Brno Running',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 5000,
    tags: ['pulmaraton', '10k'],
  },
  {
    slug: 'hradecky-pulmaraton-2026',
    country: COUNTRY,
    name: 'Hradecký půlmaraton 2026',
    description:
      'Půlmaraton v Hradci Králové vedoucí přes Labská nábřeží a městské parky. Rovinatá a rychlá trasa vhodná na osobák.',
    date_start: '2026-10-17',
    time_start: '09:30',
    city: 'Hradec Králové',
    region: 'Královéhradecký',
    lat: 50.2092,
    lng: 15.8328,
    venue: 'Velké náměstí',
    distances: [
      { label: 'Půlmaraton', km: 21.1 },
      { label: '10 km', km: 10 },
    ],
    terrain: 'road' as const,
    elevation_gain: 45,
    price_from: 550,
    price_to: 950,
    organizer: 'HK Runners',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 3500,
    tags: ['pulmaraton', '10k'],
  },
  {
    slug: 'prazsky-cross-challenge-2026',
    country: COUNTRY,
    name: 'Pražský Cross Challenge 2026',
    description:
      'Crossový závod v pražské Stromovce. Mix travnatých a zpevněných cest královským parkem. Závod Czech Running Tour.',
    date_start: '2026-11-07',
    time_start: '11:00',
    city: 'Praha',
    region: 'Praha',
    lat: 50.1057,
    lng: 14.42,
    venue: 'Stromovka',
    distances: [
      { label: '10 km', km: 10 },
      { label: '5 km', km: 5 },
      { label: 'Dětský 1 km', km: 1 },
    ],
    terrain: 'cross' as const,
    elevation_gain: 70,
    price_from: 350,
    price_to: 500,
    organizer: 'Czech Running Tour',
    status: 'confirmed' as const,
    source: 'seed',
    capacity: 2500,
    tags: ['cross', '10k', '5k', 'deti'],
  },
];

async function seed() {
  console.log(`Seeding ${races.length} races...`);

  const { data, error } = await supabase
    .from('races')
    .upsert(races, { onConflict: 'slug' })
    .select('slug');

  if (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }

  console.log(`Seeded ${data.length} races successfully.`);
  data.forEach((r) => console.log(`  - ${r.slug}`));
}

seed();
